env:
    DRONE_RPC_SECRET: ENC[AES256_GCM,data:cNBdIqO1E10vwaOcI8uOdI7psKvCng==,iv:6l8K8ict2mUQpc1muDeTJSE+FfuzLiiCg1WP31+RNz8=,tag:mzGr5yG903TbvQtwQNVsHA==,type:str]
    DRONE_GITHUB_CLIENT_ID: ENC[AES256_GCM,data:pGcFXSQ3EM+MD7voN9z81a8VTbA=,iv:a+xx5yX3AH6zwwjjjWIFLdp9tyDTCdEwyjEF6OW2blc=,tag:URT0nLvcodqEP+9eqtScEw==,type:str]
    DRONE_GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:R5UF3kF65qBUOA3AEaD0nFXFmr2MHj7UxNTGMTdyasHhDmJPyE4CEQ==,iv:hjnx3HIoZcD3RugqT0XLEZvLEtPZtZuo07e4QzeiAnI=,tag:dtGBJhDP8tixDmw0BUsNQQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/meisterlabs-prod/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2022-04-05T11:22:41Z"
          enc: CiQAuqKTw3FXnH07EJAbqHqPrHSiJkeaCcYh/x45DBr/OxL5/tgSSQB9EBTUSlEM5ZSM+xVOpHDh97orvKq9hE+bRPwCwUCpFrTUTSFCwbQW4AxtaMiejuNlrtSwSYSQzo4X9ksiGD/Ic57uvSS4b/M=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-05T11:22:42Z"
    mac: ENC[AES256_GCM,data:mx/ybhE6ygEVHTuYcMwePZ+a/Z0RvPcGWVUKp/rYZVYW8QSSU/fBH83H++mN0Ho55y+CRzRLOVSgpPc+9tu8NPnx9ZRjG+jqbN/sdro0GAf5r23fO0poH7aMh4Eol3GweMZjPTsyDH/Uv9d+BDVdk99PaW6k6YOSFHYMZCJ3CbY=,iv:2zBm8l59HEARDp9i9BXu/+4edbPpY+9YU3ebL0oL9Cg=,tag:YDfKJR6wnZJEBG5HiBDm+g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.0
