apiVersion: v1
kind: Secret
metadata:
  name: drone-license
  labels:
    {{- include "drone.labels" . | nindent 4 }}
type: Opaque
data:
  DRONE_LICENSE: |
    {{ .Values.droneLicense | b64enc | nindent 4 }}